#This file contains common configuration options for the two costmaps used in the navigation stack for more details on the parameters in this file, and a full list of the parameters used by the costmaps, please see http://www.ros.org/wiki/costmap_2d

obstacle_range: 2.5
raytrace_range: 4.0
#footprint: [[-0.12, -0.12], [-0.12, 0.12], [0.12, 0.12], [0.14, 0.0], [0.12, -0.12]]
robot_radius: 0.18
footprint_padding: 0.01
inflation_radius: 0.4

#Configuration for the sensors that the costmap will use to update a map
observation_sources: scan
scan: {data_type: LaserScan, topic: /base_scan, marking: true, clearing: true}