obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[-0.16, -0.16], [-0.16, 0.16], [0.19, 0.16], [0.24, 0.0], [0.19, -0.16]]
#footprint_padding: 0.01
robot_radius: 0.17
inflation_radius: 0.50
observation_sources: scan
scan: {data_type: LaserScan, topic: /base_scan, marking: true, clearing: true}

#Set the tolerance we're willing to have for tf transforms
#transform_tolerance: 0.3