global_costmap:
   global_frame: /world
   robot_base_frame: /base_link
   update_frequency: 3.0
   publish_frequency: 1.0
   static_map: false
   rolling_window: true
   robot_radius: 0.25
   inflation_radius: 0.26
   width: 30.0
   height: 30.0
   resolution: 0.05
   transform_tolerance: 1
