global_costmap:
   global_frame: /world
   robot_base_frame: /base_link
   update_frequency: 3.0
   publish_frequency: 1.0
   static_map: false
   rolling_window: true
   width: 24.0
   height: 24.0
   resolution: 0.1
   transform_tolerance: 1
